#!/bin/bash

set -e  # exit immediately if a command fails


IMAGE_NAME="policy-ai:1.0.0"

CONTAINER_NAME="policy-ai"


echo "PPulling latest code..."

git pull


echo " Stopping old container (if running)..."

CONTAINER_ID=$(docker ps -q --filter "ancestor=$IMAGE_NAME")

if [ -n "$CONTAINER_ID" ]; then

    docker stop $CONTAINER_ID

    docker rm $CONTAINER_ID

fi


echo "Rebuilding Docker image..."

docker build --network=host -t $IMAGE_NAME .


echo " Starting new container in detached mode with host networking..."

docker run -d --network=host $IMAGE_NAME


echo " Deployment complete!"

docker ps --filter "name=$CONTAINER_NAME"